replicaCount: 1

image:
  repository: amashk/simple-webapp-python-alpine
  tag: v1
  pullPolicy: Always

service:
  name: myapp
  type: NodePort

ingress:
  enabled: false
  annotations:
          nginx.ingress.kubernetes.io/rewrite-target: {}
  path: /
  hosts:
    - host: []
      paths: ["/"]

nodeSelector: {}
tolerations: []

appName: myapp
